$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - node_modules
  - bun.lockb
  - .tsbuildinfo
  - .gitignore
  - .next
  - drizzle
  - "**/*.svg"
  - .vscode/extensions.json
  - public
  - tsconfig.tsbuildinfo
  - branch_out
words:
  - callees
  - clsx
  - commitlint
  - compat
  - ellipsize
  - giscus
  - lockb
  - packagejson
  - tailwindcss
  - tsbuildinfo
  - tseslint
  - typecheck
